### ISSUE TITLE
Possibility for hunter feed?

### ISSUE THREAD

**Issue by llano-dan** [Xruptor/xanMortarPestle#9]
Is it possible for this addon to also handle Hunter feed pet, when hovering over food in your inventroy?

I understand if you guys want to keep this profession only, though.

**Comment by Xruptor** [comment]
Hunter feed pet?  This sounds like something for wow classic right?  Hunters on retail don't need to feed the pet.  I'm assuming what you are requesting is for classic support to allow you to feed your pet as well?

**Comment by llano-dan** [comment]
Retail. The skill still exists: https://www.wowhead.com/spell=6991/feed-pet

**Comment by Xruptor** [comment]
> Retail. The skill still exists: https://www.wowhead.com/spell=6991/feed-pet

Well I'll be a monkeys uncle.  I don't play Hunter so I didn't realize the skill was still in the retail game.  Interesting, I guess I could make one and see how I can possibly add functionality for it.  I can't promise anything as I would still need to make the toon.  On top of that I would have to make a listen of all feedable items, or at least a way I can determine if an item is feedable.

**Comment by llano-dan** [comment]
I've forked your project and I've created a first iteration of the functionality. It's using the same color as the lock pick, as you can't have both lock pick and feed pet. Secondly, it's only checking the item if it's for cooking.

**Comment by Xruptor** [comment]
> I've forked your project and I've created a first iteration of the functionality. It's using the same color as the lock pick, as you can't have both lock pick and feed pet. Secondly, it's only checking the item if it's for cooking.

This is great!  Just do a pull request you feel everything is working and I'll merge it with the live code.  I suppose that pet ability is just for food items, unless there is special feed you can use as well.

**Comment by Xruptor** [comment]
I guess everything works?  You haven't done a pull request so I can merge it with my own code.  So I guess I have to do it manually.

**Comment by llano-dan** [comment]
Sorry, wasn't quite done testing.

I've made the pull request in a state I find stable.

**Comment by Xruptor** [comment]
> Sorry, wasn't quite done testing.
> 
> I've made the pull request in a state I find stable.

Oh okay I apologize then.  I didn't see any commit updates after the initial one, so I didn't know if you were going to do the pull request or not.

**Comment by Xruptor** [comment]
Resolved #10
